#!/usr/bin/env python3
"""
QuestionForge AI: Standalone Python Excel Generator (openpyxl)
Converts extracted JSON question records into styled Excel files with embedded images.
"""
import sys
import json
import os

try:
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.drawing.image import Image as OpenpyxlImage
except ImportError:
    print("openpyxl is not installed. Run: pip install openpyxl pillow", file=sys.stderr)
    sys.exit(1)

def generate_excel_from_json(json_path, output_excel_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    project = data.get('project', {})
    questions = data.get('questions', [])

    wb = openpyxl.Workbook()
    
    # Sheet 1: Questions
    ws_q = wb.active
    ws_q.title = "Questions"
    ws_q.freeze_panes = "A2"

    headers = [
        "Q.No", "Subject", "Chapter", "Question Text",
        "Option A", "Option B", "Option C", "Option D",
        "Answer", "Type", "Difficulty", "Confidence", "Page", "Needs Review"
    ]
    ws_q.append(headers)

    # Style Header
    header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    header_font = Font(name="Segoe UI", size=11, bold=True, color="FFFFFF")
    thin_border = Border(
        left=Side(style='thin', color='E2E8F0'),
        right=Side(style='thin', color='E2E8F0'),
        top=Side(style='thin', color='E2E8F0'),
        bottom=Side(style='thin', color='E2E8F0')
    )

    for col_idx, col_name in enumerate(headers, 1):
        cell = ws_q.cell(row=1, column=col_idx)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    ws_q.row_dimensions[1].height = 28

    for idx, q in enumerate(questions, 2):
        options = {opt.get('label', '').upper(): opt.get('text', '') for opt in q.get('options', [])}
        row_data = [
            q.get('question_number', idx - 1),
            q.get('subject', 'Physics'),
            q.get('chapter', '-'),
            q.get('question_text', ''),
            options.get('A', ''),
            options.get('B', ''),
            options.get('C', ''),
            options.get('D', ''),
            q.get('answer', '-'),
            q.get('question_type', 'single_correct'),
            q.get('difficulty', 'Medium'),
            f"{q.get('confidence', 95)}%",
            ", ".join(map(str, q.get('source_pages', [1]))),
            "YES (Flagged)" if q.get('needs_review') else "OK"
        ]
        ws_q.append(row_data)
        ws_q.row_dimensions[idx].height = 35

        for col_idx in range(1, len(row_data) + 1):
            cell = ws_q.cell(row=idx, column=col_idx)
            cell.font = Font(name="Segoe UI", size=10)
            cell.alignment = Alignment(vertical="center", wrap_text=True)
            cell.border = thin_border
            if col_idx in [1, 9, 10, 11, 12, 13, 14]:
                cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    # Set Column Widths
    col_widths = {
        'A': 8, 'B': 14, 'C': 18, 'D': 45,
        'E': 25, 'F': 25, 'G': 25, 'H': 25,
        'I': 10, 'J': 16, 'K': 12, 'L': 14, 'M': 8, 'N': 14
    }
    for col, width in col_widths.items():
        ws_q.column_dimensions[col].width = width

    # Sheet 2: Metadata
    ws_meta = wb.create_sheet(title="Metadata")
    ws_meta.append(["Property", "Value"])
    ws_meta.append(["Project Name", project.get('name', 'NEET Paper')])
    ws_meta.append(["Exam Type", project.get('exam_type', 'NEET')])
    ws_meta.append(["Total Questions", len(questions)])
    ws_meta.append(["Generated By", "QuestionForge AI Python Generator"])

    # Sheet 3: Extraction Report
    ws_rep = wb.create_sheet(title="Extraction Report")
    ws_rep.append(["Q.No", "Subject", "Confidence", "Needs Review", "Review Reason"])
    for q in questions:
        ws_rep.append([
            q.get('question_number'),
            q.get('subject'),
            f"{q.get('confidence')}%",
            "YES" if q.get('needs_review') else "NO",
            q.get('review_reason', 'Clean extraction')
        ])

    wb.save(output_excel_path)
    print(f"Excel successfully created at: {output_excel_path}")

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python export_openpyxl.py <input.json> <output.xlsx>")
        sys.exit(1)
    generate_excel_from_json(sys.argv[1], sys.argv[2])
